development:
  adapter: postgresql
  encoding: unicode
  database: shortenit_development
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: shortenit_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: shortenit_test
  pool: 5
