development: &default
  adapter: postgresql
  encoding: unicode
  database: postgres
  pool: 5
  username: postgres
  password:
  host: db

test:
  <<: *default
  database: shortenit_test

development:
  adapter: postgresql
  encoding: unicode
  database: shortenit_development
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: shortenit_development
  pool: 5
